name: Release Publish

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          sed -nr 's/^\s*__version__\s*=\s*"(.*?)".*/version=\1/p' "feedcache/constants.py" >> $GITHUB_OUTPUT
          echo "ref_name=$(basename ${{ github.ref }})" >> $GITHUB_OUTPUT
          if echo "${{ github.ref }}" | grep -iP 'test|alpha|beta'; then
              echo "prerelease=true" >> $GITHUB_OUTPUT
          else
              echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python ${{ vars.FEEDCACHE_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.FEEDCACHE_PYTHON_VERSION }}

      - name: Create Python wheel and RELEASE.md
        # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
        run: |
          python -m pip install --user --break-system-packages --no-cache build
          python -m build
          # Get the last two CHANELOG.md entries
          python -c 'import re; print(re.match(r"(?sm)^(#\s.*?^##\s.*?^##\s.*?)\s*##", open("./CHANGELOG.md").read()).group(1))' > ./RELEASE.md

      - name: Create Release
        # don't forget to set the permissions for action here:
        # https://github.com/<owner>/<repo>/settings/actions
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ steps.version.outputs.prerelease }}
          name: ${{ steps.version.outputs.ref_name }}
          tag_name: ${{ github.ref }}
          body: feedcache ${{ steps.version.outputs.version }}
          body_path: ./RELEASE.md
          generate_release_notes: true
          files: |
            ./dist/feedcache-*.whl
            ./dist/feedcache-*.tar.gz
