name: Unit Tests

on:
  push:
    branches:
      - "main"
      - "actions"

  workflow_dispatch:

# see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

env: # for scripts
  python_ver: "${{ vars.FEEDCACHE_PYTHON_VERSION || '3.12' }}"
  # temporarily disabled
  FEEDCACHE_TEST_OFFLINE: "true"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        # 3.9 for Debian bullseye, 3.14.x as future version
        python-version: [ "3.9", "${{ vars.FEEDCACHE_PYTHON_VERSION || '3.12' }}", "3.14.0-alpha.1"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Say Hello
        run: |
          env | sort
          # ls -RalF
          ls -alF
          pwd
          echo "Hello Python ${python_ver}!"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: python -m pip install --user --break-system-packages --no-cache ".[all]"
      - name: Run unit tests
        run: python -m unittest discover -b -v

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.FEEDCACHE_PYTHON_VERSION || '3.12' }}
      - name: Install dependencies
        run: python -m pip install --user --break-system-packages --no-cache ".[all]" -r requirements.dev.txt
      - name: Run unit test coverage
        run: python -m coverage run -m unittest discover -b -v
      - name: Create coverage reports
        run: |
          python -m coverage xml
          python -m coverage json
          python -m coverage html
          python -m coverage report --fail-under=90
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: tmp/**
          include-hidden-files: true

      # <vanity>
      - name: Store coverage total # https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html
        run: |
          export TOTAL=$(python -c "import json;print(json.load(open('tmp/coverage.json'))['totals']['percent_covered_display'])")
          echo "coverage_total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
      - name: Coverage badge
        uses: schneegans/dynamic-badges-action@v1
        with:
          # GISTS_TOKEN is a classic GitHub personal access token with scope "gist".
          auth: ${{ secrets.GISTS_TOKEN }}
          gistID: 088b2618ff7abb97048977a4d632ed54
          filename: feedcache-coverage-badge.json
          label: Coverage
          message: ${{ env.coverage_total }}%
          minColorRange: 60
          maxColorRange: 94
          valColorRange: ${{ env.coverage_total }}
      # </vanity>
